project_name: gup
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - maintainer: Naohiro CHIKAMATSU <n.chika156@gmail.com>
    description: ddl-maker generate ddl (SQL file) from Go struct.
    homepage: https://github.com/nao1215/ddl-maker
    license: Apache License 2.0
    formats:
      - deb
      - rpm
      - apk
